/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhofinal;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isabe
 */
public class Menu extends JFrame {
    private BibliotecaDAO bibliotecaDAO;
    private Biblioteca biblioteca;
    private ClientelaDAO clientelaDAO;
    private Clientela clientela;
    private HistoricoEmprestimosDAO historicoEmprestimosDAO;
    private HistoricoEmprestimos historicoEmprestimos;
    private DefaultTableModel modelo;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        formataTabela();
        ConectaBD conectaBD = new ConectaBD();
        bibliotecaDAO = new BibliotecaDAO(conectaBD);
        biblioteca = new Biblioteca(bibliotecaDAO);
        clientelaDAO = new ClientelaDAO(conectaBD);
        clientela = new Clientela(clientelaDAO);
        historicoEmprestimosDAO = new HistoricoEmprestimosDAO(bibliotecaDAO, clientelaDAO, conectaBD);
        historicoEmprestimos = new HistoricoEmprestimos(historicoEmprestimosDAO, clientela, biblioteca);
        atualizaTudo();
    }

    //FUNCOES
    public void formataTabela() {
        modelo = new DefaultTableModel();
        tbRelatorio.setModel(modelo);
        modelo.addColumn("id_emprestimo");
        modelo.addColumn("id_cliente");
        modelo.addColumn("id_livro");
        modelo.addColumn("data_locacao");
        modelo.addColumn("data_a_devolver");
        modelo.addColumn("data_devolucao");
        modelo.addColumn("fg_quitado");
    }
    
    public void atualizaTudo() {
        rbDevendo.doClick();
        btPesquisar.doClick();
    }
    
    public void clientePadrao() {
        lbIdUsr.setVisible(false);
        txIdUsr.setVisible(false);
        btRmUsr.setVisible(false);
        btPsIdUsr.setVisible(false);
        rbUpUsr.setSelected(false);
    }
    
    public void clienteUpdate() {
        lbIdUsr.setVisible(true);
        txIdUsr.setVisible(true);
        btRmUsr.setVisible(true);
        btPsIdUsr.setVisible(true);
        
    }
    
    public void livroPadrao() {
        lbIdLvr.setVisible(false);
        txIdLvr.setVisible(false);
        btRmLvr.setVisible(false);
        btPsIdLvr.setVisible(false);
        rbUpLvr.setSelected(false);
    }
    
    public void livroUpdate() {
        lbIdLvr.setVisible(true);
        txIdLvr.setVisible(true);
        btRmLvr.setVisible(true);
        btPsIdLvr.setVisible(true);
    }
    
    public void limpaCliente() {
        txIdUsr.setText("");
        txEndereco.setText("");
        txIdade.setText("");
        txNome.setText("");
    }
    
    public void limpaLivro() {
        txAutor.setText("");
        txTitulo.setText("");
        txIdLvr.setText("");
    }
    
    public void limpaEmprestimo() {
        txPsAutor.setText("");
        txPsNome.setText("");
        txPsTitulo.setText("");
    }
    
    public void limpaTudo() {
        limpaCliente();
        limpaLivro();
        limpaEmprestimo();
    }
    
    public String formataFatura(double fatura) {
        return String.format("%.2f", fatura);
    }
    
    public void mensagemDeAviso(String msg) {
        JOptionPane.showMessageDialog(null, msg, "AVISO!", JOptionPane.WARNING_MESSAGE);
    }
    
    public void mensagemDeErro(String msg) {
        JOptionPane.showMessageDialog(null, msg, "ERRO", JOptionPane.ERROR_MESSAGE);
    }
    
    public boolean mensagemDeConfirmacao(String msg) {
        int i;
        i = JOptionPane.showConfirmDialog(null, msg, "Confirmação", JOptionPane.PLAIN_MESSAGE);
        if (i == 0)
            return true;
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonGroup1 = new javax.swing.ButtonGroup();
        abas = new javax.swing.JTabbedPane();
        pnMenu = new javax.swing.JPanel();
        lbMenuPrincipal = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        txEndereco = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        txIdade = new javax.swing.JTextField();
        lbIdade = new javax.swing.JLabel();
        btCadUsr = new javax.swing.JButton();
        lbNome1 = new javax.swing.JLabel();
        lbIdUsr = new javax.swing.JLabel();
        rbUpUsr = new javax.swing.JRadioButton();
        btRmUsr = new javax.swing.JButton();
        txIdUsr = new javax.swing.JTextField();
        btPsIdUsr = new javax.swing.JButton();
        pnSaude = new javax.swing.JPanel();
        lbPagSaude = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        btCadLiv = new javax.swing.JButton();
        txTitulo = new javax.swing.JTextField();
        txAutor = new javax.swing.JTextField();
        lbIdLvr = new javax.swing.JLabel();
        rbUpLvr = new javax.swing.JRadioButton();
        btRmLvr = new javax.swing.JButton();
        txIdLvr = new javax.swing.JTextField();
        btPsIdLvr = new javax.swing.JButton();
        pnAlimen = new javax.swing.JPanel();
        lbPagAlim = new javax.swing.JLabel();
        lbAlimenCPF = new javax.swing.JLabel();
        lbAlimenValor = new javax.swing.JLabel();
        lbAlimenCod = new javax.swing.JLabel();
        txPsNome = new javax.swing.JTextField();
        txPsTitulo = new javax.swing.JTextField();
        txPsAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCliente = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstLivro = new javax.swing.JList<>();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btEmprestar4 = new javax.swing.JButton();
        pnRelatorio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbQuitado = new javax.swing.JRadioButton();
        rbDevendo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRelatorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                abasStateChanged(evt);
            }
        });

        lbMenuPrincipal.setBackground(new java.awt.Color(204, 255, 204));
        lbMenuPrincipal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuPrincipal.setText("Cadastro de Usuário");
        lbMenuPrincipal.setOpaque(true);

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNome.setText("Nome:");

        txNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });

        txEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbEndereco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbEndereco.setText("endereço:");

        txIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdadeActionPerformed(evt);
            }
        });

        lbIdade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIdade.setText("idade:");

        btCadUsr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadUsr.setText("GRAVAR");
        btCadUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadUsrActionPerformed(evt);
            }
        });

        lbNome1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lbIdUsr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIdUsr.setText("Id:");

        rbUpUsr.setText("Atualizar Usuário Existente");
        rbUpUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUpUsrActionPerformed(evt);
            }
        });

        btRmUsr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRmUsr.setForeground(new java.awt.Color(255, 0, 51));
        btRmUsr.setText("DELETAR");
        btRmUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmUsrActionPerformed(evt);
            }
        });

        txIdUsr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txIdUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdUsrActionPerformed(evt);
            }
        });

        btPsIdUsr.setText("Pesquisar Usuario");
        btPsIdUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPsIdUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lbMenuPrincipal))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbUpUsr)
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbEndereco)
                                    .addComponent(lbNome)
                                    .addComponent(lbIdUsr)
                                    .addComponent(lbIdade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txIdade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txIdUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btCadUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                        .addComponent(lbNome1)
                        .addGap(411, 411, 411))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                        .addComponent(btRmUsr)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPsIdUsr)
                .addGap(65, 65, 65))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lbNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbUpUsr)
                .addGap(10, 10, 10)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdUsr)
                    .addComponent(txIdUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPsIdUsr)
                .addGap(29, 29, 29)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdade))
                .addGap(44, 44, 44)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadUsr)
                    .addComponent(btRmUsr))
                .addGap(32, 32, 32))
        );

        abas.addTab("Usuario", pnMenu);

        lbPagSaude.setBackground(new java.awt.Color(204, 255, 204));
        lbPagSaude.setFont(new java.awt.Font("Tahoma", 0, 38)); // NOI18N
        lbPagSaude.setText("Cadastro de Livro");
        lbPagSaude.setOpaque(true);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitulo.setText("Título:");

        lbAutor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAutor.setText("Autor:");

        btCadLiv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadLiv.setText("GRAVAR");
        btCadLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadLivActionPerformed(evt);
            }
        });

        txTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txTituloFocusLost(evt);
            }
        });
        txTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTituloActionPerformed(evt);
            }
        });

        txAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAutorActionPerformed(evt);
            }
        });

        lbIdLvr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIdLvr.setText("Id:");

        rbUpLvr.setText("Atualizar Livro Existente");
        rbUpLvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUpLvrActionPerformed(evt);
            }
        });

        btRmLvr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRmLvr.setForeground(new java.awt.Color(255, 51, 51));
        btRmLvr.setText("DELETAR");
        btRmLvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmLvrActionPerformed(evt);
            }
        });

        txIdLvr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txIdLvr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txIdLvrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txIdLvrFocusLost(evt);
            }
        });
        txIdLvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdLvrActionPerformed(evt);
            }
        });

        btPsIdLvr.setText("Pesquisar Livro");
        btPsIdLvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPsIdLvrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSaudeLayout = new javax.swing.GroupLayout(pnSaude);
        pnSaude.setLayout(pnSaudeLayout);
        pnSaudeLayout.setHorizontalGroup(
            pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSaudeLayout.createSequentialGroup()
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSaudeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rbUpLvr))
                    .addGroup(pnSaudeLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lbPagSaude)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSaudeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnSaudeLayout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnSaudeLayout.createSequentialGroup()
                        .addComponent(lbAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txAutor)
                            .addGroup(pnSaudeLayout.createSequentialGroup()
                                .addComponent(btCadLiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRmLvr)
                                .addGap(37, 37, 37))))
                    .addGroup(pnSaudeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnSaudeLayout.createSequentialGroup()
                                .addComponent(lbIdLvr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txIdLvr, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnSaudeLayout.createSequentialGroup()
                                .addComponent(btPsIdLvr)
                                .addGap(11, 11, 11)))))
                .addGap(470, 470, 470))
        );
        pnSaudeLayout.setVerticalGroup(
            pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSaudeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbPagSaude)
                .addGap(32, 32, 32)
                .addComponent(rbUpLvr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIdLvr)
                    .addComponent(txIdLvr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPsIdLvr)
                .addGap(18, 18, 18)
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(txAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadLiv)
                    .addComponent(btRmLvr))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        abas.addTab("Livro", pnSaude);

        lbPagAlim.setBackground(new java.awt.Color(204, 255, 204));
        lbPagAlim.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lbPagAlim.setText("Emprestimo");
        lbPagAlim.setOpaque(true);

        lbAlimenCPF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbAlimenCPF.setText("Nome:");

        lbAlimenValor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbAlimenValor.setText("Título:");

        lbAlimenCod.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbAlimenCod.setText("Autor");

        txPsNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txPsNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txPsNomeFocusLost(evt);
            }
        });
        txPsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPsNomeActionPerformed(evt);
            }
        });

        txPsTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPsTituloActionPerformed(evt);
            }
        });

        txPsAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPsAutorActionPerformed(evt);
            }
        });

        listaCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCliente);

        lstLivro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstLivro);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Livro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cliente");

        btEmprestar4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btEmprestar4.setText("Emprestar");
        btEmprestar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAlimenLayout = new javax.swing.GroupLayout(pnAlimen);
        pnAlimen.setLayout(pnAlimenLayout);
        pnAlimenLayout.setHorizontalGroup(
            pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlimenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addComponent(lbAlimenCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPsNome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbAlimenValor)
                            .addComponent(lbAlimenCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txPsAutor)
                            .addComponent(txPsTitulo)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEmprestar4)))
                .addGap(346, 346, 346))
            .addGroup(pnAlimenLayout.createSequentialGroup()
                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbPagAlim))
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAlimenLayout.setVerticalGroup(
            pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlimenLayout.createSequentialGroup()
                .addComponent(lbPagAlim)
                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlimenCPF)
                            .addComponent(txPsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pnAlimenLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnAlimenLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbAlimenValor)
                                    .addComponent(txPsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnAlimenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbAlimenCod)
                                    .addComponent(txPsAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlimenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEmprestar4)
                                .addGap(35, 35, 35))))))
        );

        abas.addTab("Pegar Emprestado", pnAlimen);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Relatórios");
        jLabel2.setOpaque(true);

        rbQuitado.setText("Quitado");
        rbQuitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuitadoActionPerformed(evt);
            }
        });

        rbDevendo.setText("Devendo");
        rbDevendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDevendoActionPerformed(evt);
            }
        });

        tbRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tbRelatorio);

        javax.swing.GroupLayout pnRelatorioLayout = new javax.swing.GroupLayout(pnRelatorio);
        pnRelatorio.setLayout(pnRelatorioLayout);
        pnRelatorioLayout.setHorizontalGroup(
            pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRelatorioLayout.createSequentialGroup()
                .addGroup(pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRelatorioLayout.createSequentialGroup()
                        .addGroup(pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRelatorioLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnRelatorioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbQuitado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbDevendo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnRelatorioLayout.setVerticalGroup(
            pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbQuitado)
                    .addComponent(rbDevendo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        abas.addTab("Relatório", pnRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPsAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPsAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPsAutorActionPerformed

    private void txPsTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPsTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPsTituloActionPerformed

    private void txPsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPsNomeActionPerformed

    private void txTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTituloActionPerformed

    private void txAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAutorActionPerformed

    private void btCadLivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadLivActionPerformed
        // TODO add your handling code here:
        if (!rbUpLvr.isSelected()) {
            String titulo = txTitulo.getText();
            String autor = txAutor.getText();
            biblioteca.cadastrarLivro(new Livro(titulo, autor));
            atualizaTudo();
            limpaLivro();
            mensagemDeConfirmacao("Livro cadastrado com sucesso!");
        } else {
            int id = Integer.parseInt(txIdLvr.getText());
            String titulo = txTitulo.getText();
            String autor = txAutor.getText();
            biblioteca.atualizaLivroPorId(id, titulo, autor);
            atualizaTudo();
            limpaLivro();
            mensagemDeAviso("Livro atualizado com sucesso!");
        }
    }//GEN-LAST:event_btCadLivActionPerformed

    private void txPsNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPsNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txPsNomeFocusGained

    private void txTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txTituloFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txTituloFocusGained

    private void txTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txTituloFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txTituloFocusLost

    private void txPsNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPsNomeFocusLost
        // TODO add your handling code here:         
    }//GEN-LAST:event_txPsNomeFocusLost

    private void abasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_abasStateChanged
        // TODO add your handling code here:
        limpaTudo();
        clientePadrao();
        livroPadrao();
    }//GEN-LAST:event_abasStateChanged

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        DefaultListModel listModel = new DefaultListModel();
        
        ArrayList<Cliente> clientesBuscados;
        if(!txPsNome.getText().isEmpty()) {
            clientesBuscados = clientela.buscaClientePorNome(txPsNome.getText());
        } else {
            clientesBuscados = clientela.listarClientesOrdemId();
        }
        for (Cliente cliente : clientesBuscados) {
            listModel.addElement(cliente.getId() + "; " + cliente.getNome());
        }
        listaCliente.setModel(listModel);
        
        listModel = new DefaultListModel();
        ArrayList<Livro> livrosBuscados;
        if( (!txPsAutor.getText().isEmpty()) && (txPsTitulo.getText().isEmpty()) ){
            livrosBuscados = biblioteca.buscaLivroDispPorAutor(txPsAutor.getText());
        } else if((txPsAutor.getText().isEmpty()) && (!txPsTitulo.getText().isEmpty()) ){
            livrosBuscados = biblioteca.buscaLivroDispPorTitulo(txPsTitulo.getText());
        } else {
            livrosBuscados = biblioteca.buscaLivroDispPorTituloEAutor(txPsTitulo.getText(), txPsAutor.getText());
        }
        for (Livro livro : livrosBuscados) {
            listModel.addElement(livro.getId() + "; " + livro.getTitulo()+ "; " + livro.getAutor());
        }
        lstLivro.setModel(listModel);
        
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btEmprestar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestar4ActionPerformed
        // TODO add your handling code here:
        int idCliente = Integer.parseInt(listaCliente.getSelectedValue().split(";")[0]);
        int idLivro = Integer.parseInt(lstLivro.getSelectedValue().split(";")[0]);
        historicoEmprestimos.addEmprestimo(idCliente, idLivro);
        atualizaTudo();
    }//GEN-LAST:event_btEmprestar4ActionPerformed

    private void btCadUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadUsrActionPerformed
        // TODO add your handling code here:
        if (!rbUpUsr.isSelected()) {
            String nome = txNome.getText();
            String endereco = txEndereco.getText();
            int idade = Integer.parseInt(txIdade.getText());
            clientela.addCliente(new Cliente(nome, endereco, idade));
            atualizaTudo();
            limpaCliente();
            mensagemDeConfirmacao("Cliente cadastrado com sucesso!");
        } else {
            int id = Integer.parseInt(txIdUsr.getText());
            String nome = txNome.getText();
            String endereco = txEndereco.getText();
            int idade = Integer.parseInt(txIdade.getText());
            clientela.atualizaClientePorId(id, nome, endereco, idade);
            atualizaTudo();
            limpaLivro();
            mensagemDeConfirmacao("Cliente atualizado com sucesso!");
        }
    }//GEN-LAST:event_btCadUsrActionPerformed

    private void txIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdadeActionPerformed

    private void rbDevendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDevendoActionPerformed
        // TODO add your handling code here:
        formataTabela();
        ArrayList<Emprestimo> emprestimos = null;
        if(rbDevendo.isSelected() && rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.listarEmprestimos();
        } else if (!rbDevendo.isSelected() && rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.buscaEmprestimosQuitados();
        } else if (rbDevendo.isSelected() && !rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.buscaEmprestimosNaoQuitados();
        } else {
            emprestimos = historicoEmprestimosDAO.listarEmprestimos();
        }
        int i = 0;
        for (Emprestimo emprestimo : emprestimos) {
            Object[] objeto = {emprestimo.getId(),emprestimo.getCliente().getId(),emprestimo.getLivro().getId(),
                emprestimo.getDataLocacao(), emprestimo.getDataADevolver(), emprestimo.getDataDevolucao(), emprestimo.isFgQuitado()};
            modelo.insertRow(i, objeto);
            i++;
        }
    }//GEN-LAST:event_rbDevendoActionPerformed

    private void rbQuitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuitadoActionPerformed
        // TODO add your handling code here:
        formataTabela();
        ArrayList<Emprestimo> emprestimos = null;
        if(rbDevendo.isSelected() && rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.listarEmprestimos();
        } else if (!rbDevendo.isSelected() && rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.buscaEmprestimosQuitados();
        } else if (rbDevendo.isSelected() && !rbQuitado.isSelected()) {
            emprestimos = historicoEmprestimosDAO.buscaEmprestimosNaoQuitados();
        } else {
            emprestimos = historicoEmprestimosDAO.listarEmprestimos();
        }
        int i = 0;
        for (Emprestimo emprestimo : emprestimos) {
            Object[] objeto = {emprestimo.getId(),emprestimo.getCliente().getId(),emprestimo.getLivro().getId(),
                emprestimo.getDataLocacao(), emprestimo.getDataADevolver(), emprestimo.getDataDevolucao(), emprestimo.isFgQuitado()};
            modelo.insertRow(i, objeto);
            i++;
        }
    }//GEN-LAST:event_rbQuitadoActionPerformed

    private void btRmLvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmLvrActionPerformed
        // TODO add your handling code here:
            int id = Integer.parseInt(txIdLvr.getText());
            bibliotecaDAO.rmLivro(id);
            atualizaTudo();
            limpaLivro();
            mensagemDeConfirmacao("Livro excluido com sucesso!");
        
    }//GEN-LAST:event_btRmLvrActionPerformed

    private void btRmUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmUsrActionPerformed
        // TODO add your handling code here:
            int id = Integer.parseInt(txIdUsr.getText());
            clientela.rmCliente(id);
            atualizaTudo();
            limpaLivro();
            mensagemDeConfirmacao("Usuario excluido com sucesso!");
    }//GEN-LAST:event_btRmUsrActionPerformed

    private void rbUpUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUpUsrActionPerformed
        // TODO add your handling code here:
        if(rbUpUsr.isSelected()) {
            clienteUpdate();
        } else {
            clientePadrao();
        }
    }//GEN-LAST:event_rbUpUsrActionPerformed

    private void txIdUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdUsrActionPerformed

    private void txIdLvrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txIdLvrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdLvrFocusGained

    private void txIdLvrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txIdLvrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdLvrFocusLost

    private void txIdLvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdLvrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdLvrActionPerformed

    private void btPsIdLvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPsIdLvrActionPerformed
        // TODO add your handling code here:
        int idLvr = Integer.parseInt(txIdLvr.getText());
        Optional<Livro> livro = biblioteca.buscaLivroPorId(idLvr);
        if (livro.isPresent()) {
            txTitulo.setText(livro.get().getTitulo());
            txAutor.setText(livro.get().getAutor());
        } else {
            mensagemDeErro("ID de livro nao encontrado!");
        }
    }//GEN-LAST:event_btPsIdLvrActionPerformed

    private void rbUpLvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUpLvrActionPerformed
        // TODO add your handling code here:
        if(rbUpLvr.isSelected()) {
            livroUpdate();
        } else {
            livroPadrao();
        }
    }//GEN-LAST:event_rbUpLvrActionPerformed

    private void btPsIdUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPsIdUsrActionPerformed
        // TODO add your handling code here:
        int idUsr = Integer.parseInt(txIdUsr.getText());
        Optional<Cliente> cliente = clientela.buscaClientePorId(idUsr);
        if (cliente.isPresent()) {
            txNome.setText(cliente.get().getNome());
            txEndereco.setText(cliente.get().getEndereco());
            txIdade.setText(String.valueOf(cliente.get().getIdade()));
        } else {
            mensagemDeErro("ID de livro nao encontrado!");
        }
    }//GEN-LAST:event_btPsIdUsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btCadLiv;
    private javax.swing.JButton btCadUsr;
    private javax.swing.JButton btEmprestar4;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPsIdLvr;
    private javax.swing.JButton btPsIdUsr;
    private javax.swing.JButton btRmLvr;
    private javax.swing.JButton btRmUsr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAlimenCPF;
    private javax.swing.JLabel lbAlimenCod;
    private javax.swing.JLabel lbAlimenValor;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbIdLvr;
    private javax.swing.JLabel lbIdUsr;
    private javax.swing.JLabel lbIdade;
    private javax.swing.JLabel lbMenuPrincipal;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbPagAlim;
    private javax.swing.JLabel lbPagSaude;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JList<String> listaCliente;
    private javax.swing.JList<String> lstLivro;
    private javax.swing.JPanel pnAlimen;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnRelatorio;
    private javax.swing.JPanel pnSaude;
    private javax.swing.JRadioButton rbDevendo;
    private javax.swing.JRadioButton rbQuitado;
    private javax.swing.JRadioButton rbUpLvr;
    private javax.swing.JRadioButton rbUpUsr;
    private javax.swing.JTable tbRelatorio;
    private javax.swing.JTextField txAutor;
    private javax.swing.JTextField txEndereco;
    private javax.swing.JTextField txIdLvr;
    private javax.swing.JTextField txIdUsr;
    private javax.swing.JTextField txIdade;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txPsAutor;
    private javax.swing.JTextField txPsNome;
    private javax.swing.JTextField txPsTitulo;
    private javax.swing.JTextField txTitulo;
    // End of variables declaration//GEN-END:variables
}
